---
- hosts: web1
  become: true
  become_user: root
  

  tasks:
  - name: Upgrade all apt packages
    apt: 
        upgrade: yes
        update_cache: yes
        

  
  - name: Install all required dependencies
    apt:
        name : "{{ item }}"
        state: present
    loop:
        - python3
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip 
        - python-mysqldb

  - name: Install mysql dependecies
    apt: 
        name : "{{ item }}"
        state: present
    loop:
        - mysql-server
        - mysql-client

  - name: start mysql server
    service:
        name : mysql
        state: started
        enabled: yes

  - name: Create Application Database
    mysql_db: name=employee_db state=present

  - name:  Create database user
    mysql_user:
          name: db_user
          password: Passw0rd
          priv: '*.*:ALL'
          state: present

  - name: Install flask modules 
    pip:
         name: "{{item}}"
         state: present
    
    loop:
        - flask
        -  Flask-MySQLdb

  - name: copy the app to destination
    copy: src=app.py  dest=/opt/app.py

  - name: start webserver
    shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &