---
- hosts: web1
  tasks:
  - name: Install all required dependencies
    apt:
        name : "{{ item }}"
        got: installed
    loop:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip python-mysqldb