---
- hosts: web1
  become: true
  become_user: root
  

  tasks:
  - name: Upgrade all apt packages
    apt: 
        upgrade: yes
        update_cache: yes
        

  
  - name: Install all required dependencies
    apt:
        name : "{{ item }}"
        state: present
    loop:
        - python3
        - python-setuptools
        - python-dev
        - build-essential
        - python3-pip 
        - python-mysqldb

  - include: tasks/db.yml
  - include: tasks/wflask.yml